export const stages=['Новое','Обсуждение','Согласовано','В работе','Завершено'];
export const categories=['Все категории','Дом и интерьер','Электроника','Услуги','Хобби и спорт','Одежда'];
export const seedProducts=[
{id:'chair',title:'Кресло Lounge, натуральный дуб',price:18900,oldPrice:22900,category:'Дом и интерьер',kind:'product',image:'chair.jpg',seller:'Мастерская Form',city:'Москва',rating:4.9,reviews:28,stock:5,verified:true,description:'Уютное кресло для чтения и неспешных вечеров. Деревянный каркас, мягкая обивка. Тестовое предложение: фотография иллюстративная.',delivery:'Доставка или самовывоз',status:'active',views:328},
{id:'vase',title:'Диван Soft, светлый текстиль',price:42900,category:'Дом и интерьер',kind:'product',image:'sofa.jpg',seller:'Мастерская Form',city:'Москва',rating:5,reviews:16,stock:8,verified:true,description:'Двухместный диван со съёмными чехлами. Ширина 180 см. Тестовое предложение: фотография иллюстративная.',delivery:'Доставка или самовывоз',status:'active',views:186},
{id:'interior',title:'Дизайн интерьера, в котором хочется жить',price:3500,unit:' / м²',category:'Услуги',kind:'quote',image:'interior.jpg',seller:'Анна, дизайнер',city:'Онлайн',rating:4.9,reviews:42,verified:true,description:'Обсудим ваши привычки, планировку и бюджет. Подготовим концепцию, чертежи и подбор материалов. Финальная стоимость после согласования задачи.',delivery:'Онлайн или с выездом',status:'active',views:245},
{id:'headphones',title:'Беспроводные наушники Studio',price:8900,oldPrice:10900,category:'Электроника',kind:'product',image:'headphones.jpg',seller:'Звук и форма',city:'Москва',rating:4.8,reviews:64,stock:12,verified:true,description:'Полноразмерные наушники для музыки и работы. Мягкие амбушюры, зарядный кабель в комплекте. Демонстрационный товар.',delivery:'Доставка или самовывоз',status:'active',views:412},
{id:'lamp',title:'Настольная лампа для рабочего стола',price:4200,category:'Дом и интерьер',kind:'product',image:'lamp.jpg',seller:'Светлая сторона',city:'Казань',rating:4.9,reviews:21,stock:4,verified:false,description:'Лаконичный светильник для рабочего места. Лампа входит в комплект. Фотография иллюстративная.',delivery:'Доставка по России',status:'active',views:124},
{id:'design',title:'Дизайн сайта для вашего дела',price:25000,category:'Услуги',kind:'quote',image:'workspace.jpg',seller:'Студия Точка',city:'Онлайн',rating:5,reviews:12,verified:true,description:'От структуры до готовых макетов. Начнём с обсуждения задачи и подготовим персональное предложение.',delivery:'Онлайн',status:'active',views:176},
{id:'bike',title:'Городской велосипед, размер M',price:27500,category:'Хобби и спорт',kind:'product',image:'bike.jpg',seller:'Вело Бюро',city:'Москва',rating:4.8,reviews:35,stock:2,verified:true,description:'Велосипед для поездок по городу. Предпродажная настройка включена. Тестовое предложение.',delivery:'Самовывоз',status:'active',views:203},
{id:'plant',title:'Пересадка и уход за домашними растениями',price:1800,category:'Услуги',kind:'booking',image:'plant.jpg',seller:'Зелёный кабинет',city:'Москва',rating:4.9,reviews:18,verified:false,description:'Подберём грунт, пересадим растение и расскажем об уходе. Один сеанс — 60 минут. Материалы согласовываются отдельно.',delivery:'Выезд к вам',status:'active',views:94}
];
export function createState(){return {version:0,profile:{name:'Александр',shop:'Моя мастерская',city:'Москва',bio:'Создаю вещи и помогаю воплощать идеи.',email:'',phone:''},products:structuredClone(seedProducts),favorites:[],cart:[],orders:[],tickets:[],reviews:[],events:[],messages:[{id:'welcome',thread:'demo',from:'seller',text:'Здравствуйте! Здесь можно обсудить детали заказа. Это пример переписки — сообщения в демо не отправляются реальным продавцам.',at:new Date().toISOString()}],leads:[{id:'lead1',name:'Мария К.',title:'Дизайн гостиной',price:35000,stage:'Новое',note:'Обсудить планировку',due:'Сегодня',kind:'quote'},{id:'lead2',name:'Алексей П.',title:'Комплект керамики',price:7200,stage:'Обсуждение',note:'Уточнить цвет глазури',due:'Завтра',kind:'product'},{id:'lead3',name:'Ольга С.',title:'Разработка лендинга',price:25000,stage:'В работе',note:'Показать первый вариант',due:'Сегодня',kind:'quote'}],audit:[]};}
